### ISSUE TITLE
install-boost.sh fails on macOS

### ISSUE THREAD

**Issue by dffffffff** [bluzelle/swarmDB#102]
macOS 10.13.6

How to reproduce.
Follow the instructions in the readme to install boost from the provided bash script in swarmDB/toolchain. 

Result.
~ is taken literally and the install path will end up in `/Users/username/swarmDB/toolchain/~/myboost/1_67_0/~/myboost`

A workaround is to install boost with homebrew

**Comment by ebruck** [comment]
It appears that the script does not work correctly under macOS. 

Please use this instead:

export BOOST_INSTALL_DIR="$HOME/myboost"

**Comment by dffffffff** [comment]
Same seems to be true for Debian 9.

**Comment by amastracci** [comment]
Branch merged to devel.
