### ISSUE TITLE
Problem with connection (probably the leader is down)

### ISSUE THREAD

**Issue by lotharthesavior** [bluzelle/swarmDB#49]
Hi,

I'm getting a problem with the connection. Seems that there is a problem related to the leader falling and other nodes not getting elected in time or the redirection not happening. The response is as follows:

> Could not open socket to "13.78.131.94:51010": Connection refused (61).

It happened after I insist a few times (maybe 10?) with the same request data:

```json
{
    "bzn-api": "crud",
    "cmd": "read",
    "data": {"key":"1"},
    "db-uuid": "my huge hash",
    "request-id": 4
}
```
Considerations:
- My request ID is hardcoded with "4" (is this a good idea?).
- I use to attempt new requests in every 2 or 3 seconds (sometimes I loop requesting, is it expected to accept this conditions?)
- It is a really hard bug to reproduce.

If there is any feedback on that, let me know. Thanks in advance!

**Comment by isabelsavannah** [comment]
I take it it doesn't normally fail with your setup, only occasionally?

What happens if you send many more requests (say 10/second)? Do more of them fail?

**Comment by amastracci** [comment]
@lotharthesavior Can you check this issue and see if it is happening on the latest testnet.bluzelle.com and testnet-dev.bluzelle.com?

**Comment by lotharthesavior** [comment]
Hey guys, I couldn't reproduce anymore. Thanks for the answers.
