### ISSUE TITLE
[2018-07-07 22:28:30.890888] [0x00007fff91d84380] [error]   (main.cpp:220) - could not find our http port setting!

### ISSUE THREAD

**Issue by abdulwahidgul24085** [bluzelle/swarmDB#75]
Hi, I am trying to configure the deamons bluzelle.json files, and when I am trying to run the ./swarm -c bluzelle.json I get the following error [2018-07-07 22:28:30.890888] [0x00007fff91d84380] [error]   (main.cpp:220) - could not find our http port setting!.

Thanks in advance

**Comment by amastracci** [comment]
There may be a problem with your config. Can you attach bluzelle.json?

**Comment by amastracci** [comment]
Also, attach your peerlist (peers.json)

**Comment by abdulwahidgul24085** [comment]
![screen shot 2018-07-07 at 11 57 11 pm](https://user-images.githubusercontent.com/6042059/42413808-83082510-8241-11e8-8e21-3f709bf75c8e.png)
![screen shot 2018-07-07 at 11 57 18 pm](https://user-images.githubusercontent.com/6042059/42413809-8372e9fe-8241-11e8-8bda-c6705055bca9.png)

**Comment by abdulwahidgul24085** [comment]
There is a type in the readme deals with the http_port syntax, kindly look into that. There is a missing " and additional : in the peers files
![screen shot 2018-07-07 at 11 50 12 pm](https://user-images.githubusercontent.com/6042059/42413815-c036b258-8241-11e8-9655-c10d15032867.png)

**Comment by ebruck** [comment]
@abdulwahidgul24085 The uuid in you config file must match the corresponding daemon in peers.json.

**Comment by abdulwahidgul24085** [comment]
@ebruck thank you for pointing out the uuid mismatch problem. I have managed to run 3 daemons, but  I get the following output while I am running the daemons. 
![screen shot 2018-07-08 at 2 14 07 pm](https://user-images.githubusercontent.com/6042059/42418412-630bcd02-82b9-11e8-9fa0-afd86906534d.png)
![screen shot 2018-07-08 at 2 14 21 pm](https://user-images.githubusercontent.com/6042059/42418413-63419d24-82b9-11e8-95fd-f7ac9995c3ee.png)
![screen shot 2018-07-08 at 2 14 31 pm](https://user-images.githubusercontent.com/6042059/42418414-636e103e-82b9-11e8-9676-256fc4e5dab9.png)

**Comment by ebruck** [comment]
Today your daemon's must be setup to use the same settings as they are in the peers list. That means ip, port & uuid must match with each daemon's config file.

**Comment by abdulwahidgul24085** [comment]
thanks for the help. My problem was that I configured the docker container and did not start a client to connect to it. Then I try to built it from the source, but that lead me down to this rabbit hole. I was taking part in the hack.summit() hackathon, so might have skip some step with the clock racing.
